name = "personal-video-site"
compatibility_date = "2024-01-15"
pages_build_output_dir = ".vercel/output/static"

# D1 数据库配置
[[d1_databases]]
binding = "DB"
database_name = "personal-video-site-db"
database_id = "68f44058-65cc-47b5-b289-c8fd8eef0d19"

# 环境变量
[vars]
DATABASE_URL = "sqlite://d1"
ENVIRONMENT = "development"

# 生产环境配置
[env.production]
vars = { ENVIRONMENT = "production", DATABASE_URL = "sqlite://d1" }

# 生产环境 D1 数据库
[[env.production.d1_databases]]
binding = "DB"
database_name = "personal-video-site-db"
database_id = "68f44058-65cc-47b5-b289-c8fd8eef0d19"