name = "personal-video-site"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[env.production]
# D1 数据库绑定
# 运行 `wrangler d1 create personal-video-site-db` 创建数据库
# 然后将返回的数据库 ID 填入下面的 database_id
[[env.production.d1_databases]]
binding = "DB"
database_name = "personal-video-site-db"
database_id = "68f44058-65cc-47b5-b289-c8fd8eef0d19"

[env.preview]
# 预览环境可以使用相同的数据库或创建单独的预览数据库
[[env.preview.d1_databases]]
binding = "DB"
database_name = "personal-video-site-db"
database_id = "68f44058-65cc-47b5-b289-c8fd8eef0d19"