name = "personal-video-site"
compatibility_date = "2024-01-15"
pages_build_output_dir = ".vercel/output/static"

# 生产环境配置
[env.production]
vars = { ENVIRONMENT = "production" }

# D1 数据库配置
[[d1_databases]]
binding = "DB"
database_name = "personal-video-site-db"
database_id = "your-database-id-here"

# 环境变量
[vars]
DATABASE_URL = "your-d1-database-url"
ENVIRONMENT = "development"