name = "personal-video-site"
compatibility_date = "2024-09-20"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm install --legacy-peer-deps && npm run build && npx @cloudflare/next-on-pages"
cwd = "."

[build.upload]
format = "modules"
directory = ".vercel/output/static"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]

[vars]
NODE_ENV = "production"

# Cloudflare Pages 配置
[env.production]
# 生产环境变量
NEXT_PUBLIC_BASE_URL = "https://personal-video-site.pages.dev"

[env.preview]
# 预览环境变量
NEXT_PUBLIC_BASE_URL = "https://preview.personal-video-site.pages.dev"

# 缓存配置
[[rules]]
action = "cache"
cache_level = "cache_everything"
edge_cache_ttl = 86400
browser_cache_ttl = 86400
[rules.match]
url = "*/api/proxy-image*"

[[rules]]
action = "cache"
cache_level = "cache_everything"
edge_cache_ttl = 31536000
browser_cache_ttl = 31536000
[rules.match]
url = "*/covers/*"

[[rules]]
action = "cache"
cache_level = "cache_everything"
edge_cache_ttl = 31536000
browser_cache_ttl = 31536000
[rules.match]
url = "*/backgrounds/*"